#!/usr/bin/env python3
"""Generate docs/bubble-schema.md from the Bubble app export (no secrets)."""
import json, sys, os
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
src = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, 'bubble-export/ai-anesthesia-board-prep.bubble')
d = json.load(open(src))
out = []
w = out.append

def typ(v):
    return v.replace('custom.', '').replace('option.', 'option:').replace('list.', 'list of ')

w("# Bubble app schema — ai-anesthesia-board-prep\n")
w("Generated by `scripts/export-schema.py` from the Bubble export. Field ids are the keys used by the Data API.\n")

w("## Pages\n")
for k, p in d['pages'].items():
    title = p.get('properties', {}).get('title', {}).get('entries', {}).get('0', '')
    w(f"- `{p.get('name', k)}` — {title}")
w("")

w("## Data types\n")
for name in sorted(d['user_types']):
    t = d['user_types'][name]
    if t.get('deleted'): continue
    w(f"### `{name}` — {t.get('display', '')}\n")
    fields = t.get('fields', {})
    live = {k: v for k, v in fields.items() if not v.get('deleted')}
    w("| Data API id | Display | Type | Default |")
    w("|---|---|---|---|")
    for fid, f in sorted(live.items()):
        w(f"| `{fid}` | {f.get('display','')} | {typ(f.get('value',''))} | {f.get('default_val','')} |")
    w("")

w("## Option sets\n")
for name in sorted(d['option_sets']):
    s = d['option_sets'][name]
    vals = s.get('values', {})
    disp = [v.get('display', '') for v in vals.values()]
    attrs = sorted({a for v in vals.values() for a in v if a not in ('display',)})
    w(f"- **`{name}`** ({s.get('display','')}): {', '.join(disp)}" + (f"  \n  attributes: {', '.join(attrs)}" if attrs else ""))
w("")

w("## Backend (API) workflows\n")
w("| Name | Exposed | Params | Actions |")
w("|---|---|---|---|")
for k, a in sorted(d['api'].items(), key=lambda kv: kv[1].get('name', '')):
    if a.get('type') != 'APIEvent': continue
    p = a.get('properties', {})
    params = p.get('parameters', {})
    pl = ', '.join(f"{v.get('key')}:{typ(str(v.get('value','')))}" for v in params.values()) if isinstance(params, dict) else ''
    w(f"| {a.get('name','')} (`{p.get('wf_name','')}`) | {'yes' if p.get('expose') else ''} | {pl} | {len(a.get('actions',{}))} |")
w("")

open(os.path.join(ROOT, 'docs/bubble-schema.md'), 'w').write('\n'.join(out))
print("wrote docs/bubble-schema.md", len('\n'.join(out)), "bytes")
